"""add_fabric_simulation

Revision ID: 324857449106
Revises: b2c3d4e5f6a7
Create Date: 2026-05-30 15:12:06.228333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324857449106'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fabric_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fabric_type', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('stiffness', sa.Integer(), nullable=False),
    sa.Column('render_base64', sa.Text(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fabric_simulations_id'), 'fabric_simulations', ['id'], unique=False)
    op.drop_index(op.f('ix_style_critiques_user_id'), table_name='style_critiques')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_style_critiques_user_id'), 'style_critiques', ['user_id'], unique=False)
    op.drop_index(op.f('ix_fabric_simulations_id'), table_name='fabric_simulations')
    op.drop_table('fabric_simulations')
    # ### end Alembic commands ###
