FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY common /app/common
COPY audit /app/audit

EXPOSE 8005

CMD ["uvicorn", "audit.main:app", "--host", "0.0.0.0", "--port", "8005"]
